export const AUTH_SUBMIT_LOGIN = 'AUTH_SUBMIT_LOGIN'
export const AUTH_USER_HANDLE_SUCCEEDED = 'AUTH_USER_HANDLE_SUCCEEDED'
export const AUTH_USER_HANDLE_FAILED = 'AUTH_USER_HANDLE_FAILED'
export const AUTH_VERIFY_TOKEN = 'AUTH_VERIFY_TOKEN'
